---
- name: Install libraries
  become: yes
  apt:
    update_cache: yes
    pkg:
    - libevent-dev 
    - libzmq3-dev
- name: Install tools
  become: yes
  apt:
    update_cache: yes
    pkg:
    - sysstat
    - msr-tools
    - linux-tools-common
    - linux-tools-generic
    - linux-tools-4.15.0-159-generic
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04' 
